# Generated by Django 6.0.4 on 2026-04-16 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números.', regex='^\\+?\\d+$')]),
        ),
    ]
